import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar9 } from "@/components/Navbar9";
import { Footer8 } from "@/components/Footer8";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar9 />
        {children}
        <Footer8 />
      </body>
    </html>
  );
}
